name: Build release artifact
on: [push, pull_request]

jobs:
  build-release:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - name: Publish release build
      run: dotnet publish -c Release -p:PublishProfile=Standalone
    - name: Print published executable hash
      run: (Get-FileHash src/bin/Release/standalone/Win10BloatRemover.exe).Hash
    - name: Copy Readme and License near published executable
      run: cp @('LICENSE', 'README.md') -Destination src/bin/Release/standalone
    - name: Upload release files
      uses: actions/upload-artifact@v3
      with:
        name: Release ZIP
        path: src/bin/Release/standalone/*
        if-no-files-found: error
